
services:
  db:
    image: mysql
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
      # command: --init-file /docker-entrypoint-initdb.d/main.sql
    volumes:
      - ./:/sql/
    working_dir: /sql/
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3
    ports:
      - "3306:3306"
