name: CI

on: [push]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install composer and dependencies
        working-directory: ./app-backend
        uses: php-actions/composer@v6

      - name: PHPUnit Tests
        working-directory: ./app-backend
        uses: php-actions/phpunit@v3
        env:
          XDEBUG_MODE: coverage
        with:
          bootstrap: vendor/autoload.php
          configuration: phpunit.xml
          php_extensions: xdebug
          args: tests --coverage-clover ./coverage.xml

      - name: Upload to Codecov
        working-directory: ./app-backend
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODE_COV_TOKEN }}
          files: ./coverage.xml
          verbose: true
