FROM node:18-alpine
WORKDIR /react-docker-example/
COPY public/ /react-docker-example/public
COPY src/ /react-docker-example/src
COPY package.json /react-docker-example/
COPY Istruzioni.sh /react-docker-example/
CMD ["sh", "Istruzioni.sh"]
