FROM archlinux:base-devel-20240101.0.204074
RUN pacman -Sy --noconfirm --needed \
  php hunspell hunspell-it \
  texlive \
  texlive-latex \
  texlive-binextra \
  texlive-latexrecommended \
  texlive-latexextra \
  texlive-langitalian

