version: '3.7'
services:

    frontend:
      build:
        context: ./app-frontend 
      ports:
        - "80:80"
      networks:
        - app-network

    backend:
      build:
        context: ./app-backend/
      restart: unless-stopped
      environment:
        MYSQL_DATABASE: easymeal
        MYSQL_ROOT_PASSWORD: root
        MYSQL_PASSWORD: root
        MYSQL_USER: ${DB_USERNAME}
      working_dir: /var/www
      volumes:
        - ./app-backend:/var/www
      ports:
        - "8000:8000"
      networks:
        - app-network
        - db

    db:
      image: mysql
      restart: unless-stopped
      environment:
        MYSQL_DATABASE: easymeal
        MYSQL_ROOT_PASSWORD: root
        MYSQL_PASSWORD: root
      volumes:
        - ./initdb:/docker-entrypoint-initdb.d
      ports:
        - 3306:3306
      networks:
        - db

    phpmyadmin:
      image: phpmyadmin/phpmyadmin
      restart: unless-stopped
      environment:
        PMA_HOST: db
        MYSQL_ROOT_PASSWORD: root
      depends_on:
        - db
      ports:
        - 8443:80
      networks:
        - db

networks:
  app-network:
    driver: bridge
  db: