name: Frontend Tests
on: [push]
jobs:
  Jest:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./mvp-codice/2-rct/
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - run: npm ci
      - run: npm run test

