on: push
name: Laravel
jobs:
  phpunit:
    runs-on: ubuntu-latest
    container:
      image: kirschbaumdevelopment/laravel-test-runner:8.3
 
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: test
        ports:
          - 33306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
 
    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1
 
    - name: Install composer dependencies
      working-directory: ./app-backend
      run: |
        composer install --no-scripts
 
    - name: Prepare Laravel Application
      working-directory: ./app-backend
      run: |
        cp .env.ci .env
        php artisan key:generate
 
    - name: Run Testsuite
      working-directory: ./app-backend
      run: vendor/bin/phpunit tests/ --migrate-configuration

    - name: Install XDebug
      run: apt-get install -y php-xdebug

    - name: PHPUnit Tests
       env:
         XDEBUG_MODE: coverage
       with:
         bootstrap: app-backend/vendor/autoload.php
         configuration: app-backend/phpunit.xml
         args: app-backend/tests --coverage-clover ./app-backend/coverage.xml

     - name: Upload to Codecov
       uses: codecov/codecov-action@v2
       with:
         token: ${{ secrets.CODE_COV_TOKEN }}
         files: ./app-backend/coverage.xml
         verbose: true
