name: Validatore TMesser
on:
  push:
    - '*doc-*'

jobs:
  TMesser:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run:  sudo apt install -y php
        name: Installazione PHP
      - uses: xu-cheng/latex-action@v3
        name: Compilazione Latex
        with:
          work_in_root_file_dir: true
          root_file: |
            ./rtb/analisi-requisiti/main.tex
            ./rtb/glossario/main.tex
            ./rtb/norme-di-progetto/main.tex
            ./rtb/piano-di-progetto/main.tex
            ./rtb/piano-di-qualifica/main.tex
