name: Validatore TMesser

on:
  push:
    branches:
      - "*doc-*"
      - "documenti-corretti"
      - "documentazione-main"

jobs:
  TMesser:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - run:  sudo apt install -y php hunspell hunspell-it hunspell-en-us
        name: Installazione PHP

      - run:  cd ./rtb/ && php validatore.php --action
        name: Esecuzione del validatore

      - uses: xu-cheng/latex-action@v3
        name: Compilazione Latex
        with:
          work_in_root_file_dir: true
          root_file: |
            ./rtb/analisi-requisiti/main.tex
            ./rtb/glossario/main.tex
            ./rtb/norme-di-progetto/main.tex
            ./rtb/piano-di-progetto/main.tex
            ./rtb/piano-di-qualifica/main.tex
