name: React

on:
  push:
    branches: [laravel-action]
  pull_request:
    branches: [laravel-action]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        working-directory: ./mvp-codice/2-rct/
        run: npm install

      - name: Run the tests and generate coverage report
        run: npm test -- --coverage

      - name: Upload coverage to Codecov
        working-directory: ./mvp-codice/2-rct/
        uses: codecov/codecov-action@v1

      - name: Build
        working-directory: ./mvp-codice/2-rct/
        run: npm run build
