name: React

on: push

env:
  CI: false

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        working-directory: ./app-frontend
        run: npm install

      - name: Run the tests and generate coverage report
        working-directory: ./app-frontend
        run: npm test -- --coverage

      - name: Codecov
        uses: codecov/codecov-action@v4.3.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Build
        working-directory: ./app-frontend
        run: npm run build
